"""initial migration

Revision ID: 8a8a299e0390
Revises: 
Create Date: 2017-02-21 18:29:10.883712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8a299e0390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_lyrics', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lyrics')
    # ### end Alembic commands ###
